# Generated by Django 6.0.7 on 2026-07-25 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Agence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("code_agence", models.CharField(max_length=10, unique=True)),
            ],
            options={
                "ordering": ["code_agence"],
            },
        ),
        migrations.CreateModel(
            name="CategorieCompte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("libelle", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Catégorie de compte",
                "verbose_name_plural": "Catégories de compte",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="TypeCarte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("libelle", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "Type de carte",
                "verbose_name_plural": "Types de carte",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="TypeCreditGestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("libelle", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "Sous-type de crédit gestion",
                "verbose_name_plural": "Sous-types de crédit gestion",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="TypePlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("libelle", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Type de placement",
                "verbose_name_plural": "Types de placement",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="Credoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sens",
                    models.CharField(
                        choices=[("import", "Import"), ("export", "Export")],
                        max_length=10,
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=3, max_digits=15)),
                ("date", models.DateField()),
                (
                    "agence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kpis.agence"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Admin (Siège)"),
                            ("chef_agence", "Chef d'Agence"),
                            ("employe", "Employé"),
                        ],
                        default="employe",
                        max_length=20,
                    ),
                ),
                ("peut_gerer_comptes", models.BooleanField(default=False)),
                ("peut_gerer_credits", models.BooleanField(default=False)),
                ("peut_gerer_tpe", models.BooleanField(default=False)),
                ("peut_gerer_cartes", models.BooleanField(default=False)),
                ("peut_gerer_credoc", models.BooleanField(default=False)),
                ("peut_gerer_placements", models.BooleanField(default=False)),
                (
                    "agence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kpis.agence",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompteClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.PositiveIntegerField()),
                ("nombre", models.PositiveIntegerField(default=0)),
                (
                    "montant",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True
                    ),
                ),
                (
                    "agence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kpis.agence"
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="kpis.categoriecompte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compte client",
                "verbose_name_plural": "Comptes clients",
                "unique_together": {("agence", "categorie", "annee")},
            },
        ),
        migrations.CreateModel(
            name="Credit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("voiture", "Crédit Voiture"),
                            ("mobilier", "Crédit Mobilier"),
                            ("consommation", "Crédit Consommation"),
                            ("gestion", "Crédit Gestion"),
                            ("morale_non_terme", "Crédit Morale Non Terme"),
                            ("engagement_signature", "Engagement par Signature"),
                        ],
                        max_length=30,
                    ),
                ),
                ("annee", models.PositiveIntegerField()),
                ("nombre", models.PositiveIntegerField(default=0)),
                (
                    "montant",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True
                    ),
                ),
                (
                    "agence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kpis.agence"
                    ),
                ),
                (
                    "sous_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="kpis.typecreditgestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crédit",
                "verbose_name_plural": "Crédits",
                "unique_together": {("agence", "categorie", "sous_type", "annee")},
            },
        ),
        migrations.CreateModel(
            name="Placement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.PositiveIntegerField()),
                ("nombre", models.PositiveIntegerField(default=0)),
                (
                    "montant",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True
                    ),
                ),
                (
                    "agence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kpis.agence"
                    ),
                ),
                (
                    "type_placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="kpis.typeplacement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Placement",
                "verbose_name_plural": "Placements",
                "unique_together": {("agence", "type_placement", "annee")},
            },
        ),
        migrations.CreateModel(
            name="VenteCarte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.PositiveIntegerField()),
                ("nombre", models.PositiveIntegerField(default=0)),
                (
                    "montant",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True
                    ),
                ),
                (
                    "agence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kpis.agence"
                    ),
                ),
                (
                    "type_carte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="kpis.typecarte"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vente carte",
                "verbose_name_plural": "Ventes cartes",
                "unique_together": {("agence", "type_carte", "annee")},
            },
        ),
        migrations.CreateModel(
            name="VenteTPE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annee", models.PositiveIntegerField()),
                ("nombre", models.PositiveIntegerField(default=0)),
                (
                    "montant",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=15, null=True
                    ),
                ),
                (
                    "agence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="kpis.agence"
                    ),
                ),
            ],
            options={
                "verbose_name": "Vente TPE",
                "verbose_name_plural": "Ventes TPE",
                "unique_together": {("agence", "annee")},
            },
        ),
    ]
